CityName:
 - ["Port Royale", "Desc"]
 - ["Tortuga", "Desc"]
 - ["Belle île", "Desc"]
 - ["Mirage", "Desc"]
 - ["Blue Lagon", "Desc"]
 - ["dunkerque", "Desc"]
 - ["Saigon", "Desc"]
 - ["Maracaibo", "Desc"]
 - ["Fort de la Roche", "Desc"]
 - ["Mahebourg", "Desc"]
 - ["Guajira", "Desc"]
 - ["Vézoul", "Desc"]
ResourceName: # [nomResource, niveau, prix de base]
 - ["Bois", 1, 10]
 - ["Coton", 1, 10]
 - ["Tissu", 1, 10]
 - ["Tabac", 1, 10]
 - ["Rhum", 1, 10]
 - ["Fer", 1, 10]
 - ["Armes", 2, 100]
 - ["Rubis", 2, 100]
 - ["Ivoire", 2, 100]
 - ["Soie", 2, 100]
 - ["Diamant", 3, 1000]
 - ["Opium", 3, 1000]
BoatName:
 - "Le Petit Bateau en Mousse"
 - "L'Arcadia"
 - "Atlantis"
 - "Le Goéland"
 - "Le Titanic"
TraderName:
 - ["pierre", "Desc"]
 - ["paul", "Desc"]
 - ["bill", "Desc"]
 - ["luigi", "Desc"]
 - ["mario", "Desc"]
 - ["momo", "Desc"]
 - ["jhon", "Desc"]
 - ["fred", "Desc"]
 - ["wil", "Desc"]
 - ["nic", "Desc"]
 - ["franck", "Desc"]
 - ["jean", "Desc"]